// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  AUTH: {
    LOGIN_API:"http://localhost:4040/api/authentification",
    ME_API:"http://localhost:4040/api/users/moi",
    LOGOUT_API:"http://localhost:4040/api/logout",
    REFRESH_TOKEN_API:"http://localhost:4040/api/refresh-token",
    LIST_MY_ROLES:"http://localhost:4040/api/check-my-roles",
    CHECK_IF_I_AM_LIGIN:"http://localhost:4040/api/check-if-am-login",
    PREFERENCE_API: "http://localhost:4040/api/preference"
  },
  ORGANIGRAMME: {
    COMMUNES_API:"http://localhost:4040/api/communes",
    CATEGORIES_STRUCTURE_API: "http://localhost:4040/api/categorie-structures",
    BUREAUX_API:"http://localhost:4040/api/bureaux",
    SERVICES_API:"http://localhost:4040/api/services",
    STRUCTURES_API:"http://localhost:4040/api/structures",
    PREFERENCE_API:"http://localhost:4040/api/preference",
    LIVRE_FONCIER_API: "http://localhost:4040/api/livre_foncier",
  },
  REAL_TIME: {
    GLOBAL_INFO:"http://localhost:4040/api/stats/global-sessions-infos"

  },
  TERRITOIRE: {
    REGIONS_API:"http://localhost:4040/api/regions",
    PROVINCES_API:"http://localhost:4040/api/provinces",
    ARRONDISSEMENTS_API: "http://localhost:4040/api/arrondissements",
    COMMUNES_API: "http://localhost:4040/api/communes",
    LOCALITES_API:"http://localhost:4040/api/localites",
    PARCELLE_API:"http://localhost:4040/api/parcelles",
    ILOT_API:"http://localhost:4040/api/ilots",
  },
  CONFIGURATION: {
    TYPE_IMMEUBLE_API: "http://localhost:4040/api/type-immeuble",
    TYPE_DOCUMENT_API: "http://localhost:4040/api/type-document",
    DESTINATION_PARCELLE_API: "http://localhost:4040/api/destination",
    TYPE_BATIMENT_API: "http://localhost:4040/api/type-batiment",
    QUARTIER_API: "http://localhost:4040/api/quartier",
    ATTRIBUTION_SOURCE_API:  "http://localhost:4040/api/cession-source",
    ARRONDISSEMENT_ZONE_API: "http://localhost:4040/api/arrondissement-zone",
    AP_TYPE_API: "http://localhost:4040/api/amenagement-particulier-type",
    CATEGORIE_IMMEUBLE_API:"http://localhost:4040/api/categorie-immeuble",
    DROIT_IMMOBILIER_API:"http://localhost:4040/api/droit-immobilier",
    TYPE_TRANSITION_API:"http://localhost:4040/api/type-transition",
    MOTIF_REJET_API:"http://localhost:4040/api/motif-rejet",
    DOMAINE_FONCTIONNEL_API:"http://localhost:4040/api/domaine-fonctionnel",
    PLAN_SOURCE_API: "http://localhost:4040/api/plan-source",
    COEFFICIENT_API:  "http://localhost:4040/api/coefficient-vetus",
    PARCELLE_BAREME_API: "http://localhost:4040/api/bareme-parcelle",
    NATURE_IMPOT_API: "http://localhost:4040/api/nature-impot",
    TYPE_TITRE_RECETTE_API: "http://localhost:4040/api/type-titre-recette",
    ELEMENT_LIQUIDATION_API: "http://localhost:4040/api/element-liquidation",
    PACKAGE_IMPOT_API: "http://localhost:4040/api/package-impot",
    BATIMENT_API: "http://localhost:4040/api/batiment",
    IMMEUBLE_API:  "http://localhost:4040/api/immeuble",
    AMENAGEMENT_PARTICULIER_API:"http://localhost:4040/api/amenagement-particulier",
    PARCELLE_DELIMITATION_API:"http://localhost:4040/api/parcelle-delimitation",
    EXONERATION_CATEGORIE_API: "http://localhost:4040/api/exoneration-categorie",
    MODE_REGLEMENT_API: "http://localhost:4040/api/mode-reglement",
    TITRE_RECETTE_API: "http://localhost:4040/api/titre-recette",
    EXONERATION_API: "http://localhost:4040/api/exoneration",
    SYSTEM_IMPOSITION_API: "http://localhost:4040/api/system-imposition",
    DEGRE_SUCCESSORAL_API: "http://localhost:4040/api/degre-successoral",
    EXERCICE_FISCALE_API: "http://localhost:4040/api/exercice-fiscale",
    BAREME_IMPOT_API:"http://localhost:4040/api/bareme-impot",
    FORMULE_API: "http://localhost:4040/api/formule",
    CATEGORIE_PIECE_PROCESSUS_API: "http://localhost:4040/api/categorie-piece-processus",
    MANDAT_API: "http://localhost:4040/api/mandats",
    CYLE_DE_VIE: "http://localhost:4040/api/cyle-de-vie",
    CALENDRIER_FISCALE_API: "http://localhost:4040/api/calendrier-fiscale",
    QUITTANCE_SINTAX: "http://localhost:4040/api/quittance",

  },
  PROCESSUS: {
    PLAN_CADASTRAL_SECTIONNEMENT:"http://localhost:4040/api/processus/plan-cadastral-sectionnement",
    PLAN_CADASTRAL_AMENAGEMENT:"http://localhost:4040/api/processus/plan-cadastral-amenagement",
    PLAN_CADASTRAL_LOTISSEMENT:"http://localhost:4040/api/processus/plan-cadastral-lotissement",
    PLAN_CADASTRAL_MAJ_PLAN_CADASTRE:"http://localhost:4040/api/processus/mise-a-jour-plan-cadastral",
    PLAN_CADASTRAL_MORCELLEMENT:"http://localhost:4040/api/processus/plan-cadastral-morcellement",
    PLAN_CADASTRAL_FUSION:"http://localhost:4040/api/processus/plan-cadastral-fusion",
    PLAN_CADASTRAL_TOURNEE_DE_CONSERVATION:"http://localhost:4040/api/processus/plan-cadastral-tournee-de-conservation",
    TRANSITION:"http://localhost:4040/api/transitions",
    HISTORIQUE:"http://localhost:4040/api/historiques",
    PPROCESSUS:"http://localhost:4040/api/processus",
     BORNAGE_DELIMITATION:"http://localhost:4040/api/processus/bornage-delimitation",
    CONTRIBUTION_FONCIERE: "http://localhost:4040/api/processus/contribution-fonciere",
    PROCESSUS_MANDAT_API:"http://localhost:4040/api/processus/mandat",
    EXONERATION_API: "http://localhost:4040/api/processus/exoneration",

  },
  SAISIE_DIFFEREE: {

    SAISIE_DIFFEREE_ATTRIBUTION_API: "http://localhost:4040/api/processus/saisie-differee/attribution",
    SAISIE_DIFFEREE_MUTATION_API: "http://localhost:4040/api/processus/saisie-differee/mutation",
    SAISIE_DIFFEREE_AFFECTATION_API: "http://localhost:4040/api/processus/saisie-differee/affectation",
    SAISIE_DIFFEREE_RETRAIT_API: "http://localhost:4040/api/processus/saisie-differee/retrait",
    SAISIE_DIFFEREE_DEMANDE_DOCUMENT_API: "http://localhost:4040/api/processus/saisie-differee/demandes-documents",
    SAISIE_DIFFEREE_DELIVRANCE_AAP_API: "http://localhost:4040/api/processus/attestation_attribution_parcelle",
    SAISIE_DIFFEREE_MAJ_API:"http://localhost:4040/api/processus/saisie-differee/mise-a-jour-plan-cadastral",
    SAISIE_DIFFEREE_PV_ATTRIBUTION_API:"http://localhost:4040/api/processus/saisie-differee/entete-pv",
    SAISIE_DIFFEREE_ATTRIBUTION_CONTEXTE_API:"http://localhost:4040/api/SaisieDiffereeAttributionContexte",

    SAISIE_DIFFEREE_SECTIONNEMENT_API:"http://localhost:4040/api/processus/saisie-differee/sectionnement",
   },
  APPLICATION: {
    MENU_USER_API:"http://localhost:4040/api/menu-users",
    UPLOAD_FILE_API:"http://localhost:4040/api/file/upload",
    UPLOAD_FILE_API_PUBLIC:"http://localhost:4040/api/file/public/upload",
    AVATAR_API:"http://localhost:4040/api/file/download",
    STATUS_JURIDIQUE_API:"http://localhost:4040/api/status-juridique",
    CATEGORIES_PIECE:"http://localhost:4040/api/categorie-piece",
    CATEGORIES_PIECE_PROCESSUS:"http://localhost:4040/api/categorie-piece-processus",
    CIVILITES_API:"http://localhost:4040/api/civilite",
    CATEGORIES_ACTEUR:"http://localhost:4040/api/categorie-acteur",
    FILTRE_RECHERCHE_AVANCE_API:"http://localhost:4040/api/filtre-recherche-avance",
    PARAMETRES_API: "http://localhost:4040/api/parametres",
    INDIVISIONS_REALATION_API: "http://localhost:4040/api/indivision-relation",
    EXPORT_API: "http://localhost:4040/api/reports",
    EXPORT_PROCESSUS_DOSSIER: "http://localhost:4040/api/printer_report",
    TEMPLATE_EMAIL_API: "http://localhost:4040/api/template-email",
    AUDIT: "http://localhost:4040/api/audits",
    RECUPERATION_COMPTE: "http://localhost:4040/api/recover-password",
    MENU_API: "http://localhost:4040/api/menu",
    INDEXATION: "http://localhost:4040/api/indexation",
    NOTIFICATION_API: "http://localhost:4040/api/notifications"
  },
  SECURITY: {
    ROLES_API:"http://localhost:4040/api/roles",
    PERMISSIONS_API:"http://localhost:4040/api/permissions",
    PROFILES_API: "http://localhost:4040/api/profils",
    OTP_CONFIG_API: "http://localhost:4040/api/user-profil-edition/otp/config",
    OTP_CONFIG_VALIDATION_API: "http://localhost:4040/api/user-profil-edition/otp/validate-config",
    OTP_RESET_API: "http://localhost:4040/api/user-profil-edition/otp/reset",
    OTP_CHECK_API: "http://localhost:4040/api/user-profil-edition/otp/check",
    OTP_READER_CHECK_API: "http://localhost:4040/api/user-profil-edition/otp/reader-for-check",
  },
  USERS: {
    ACTEURS_API: "http://localhost:4040/api/acteurs",
    AGENTS_API:"http://localhost:4040/api/agents",
    CONTRIBUABLE_MORAL_API:"http://localhost:4040/api/contribuable-morales",
    CONTRIBUABLE_PHYSIQUE_API:"http://localhost:4040/api/contribuable-physiques",
    CONTRIBUABLE_API:"http://localhost:4040/api/contribuables",
    TRANSITION_FONCTIONNELLE_API:"http://localhost:4040/api/transition-fonctionnelle",

    CONTRIBUABLE_CHECK_API:"http://localhost:4040/api/contribuables/check",
    USER_PROFIL_EDITION_AVATAR: "http://localhost:4040/api/user-profil-edition/avatar",
    USER_PROFIL_EDITION_EMAIL: "http://localhost:4040/api/user-profil-edition/emails",
    USER_PROFIL_EDITION_ADRESSE:"http://localhost:4040/api/user-profil-edition/adresses",
    USER_PROFIL_EDITION_TELEPHONE:"http://localhost:4040/api/user-profil-edition/telephones",
    USER_PROFIL_EDITION_CREDENTIAL:"http://localhost:4040/api/user-profil-edition/credentials",
    NEW_COMPTE: "http://localhost:4040/api/processus/creation-compte-contribuable",
    NEW_COMPTE_PUBLIC: "http://localhost:4040/api/processus/creation-compte-contribuable/public",

    USER_PROFIL_DOSSIER_MOI_BORNAGE: "http://localhost:4040/api/users/moi/dossiers/bornage",
    USER_PROFIL_DOSSIER_MOI_ATTRIBUTION: "http://localhost:4040/api/users/moi/dossiers/attribution",
    USER_PROFIL_DOSSIER_MOI_RETRAIT: "http://localhost:4040/api/users/moi/dossiers/retrait",
    USER_PROFIL_DOSSIER_MOI_EXONERATION: "http://localhost:4040/api/users/moi/dossiers/exoneration",
    USER_PROFIL_DOSSIER_MOI_MANDAT: "http://localhost:4040/api/users/moi/dossiers/mandat",
    USER_PROFIL_DOSSIER_MOI_MUTATION: "http://localhost:4040/api/users/moi/dossiers/mutation",
    USER_PROFIL_DOSSIER_MOI_MORCELLEMENT: "http://localhost:4040/api/users/moi/dossiers/morcellement",
    USER_PROFIL_DOSSIER_MOI_CONTRIBUTION: "http://localhost:4040/api/users/moi/dossiers/contribution-fonciere",
    USER_PROFIL_DOSSIER_MOI_FUSION: "http://localhost:4040/api/users/moi/dossiers/fusion",
    USER_PROFIL_DOSSIER_MOI_MISE_A_JOUR: "http://localhost:4040/api/users/moi/dossiers/mise-a-jour",
    USER_PROFIL_DOSSIER_MOI_AMENAGEMENT: "http://localhost:4040/api/users/moi/dossiers/amenagement",
    USER_PROFIL_DOSSIER_MOI_LOTISSEMENT: "http://localhost:4040/api/users/moi/dossiers/lotissement",
    USER_PROFIL_DOSSIER_MOI_DEMANDE_DOCUMENT: "http://localhost:4040/api/users/moi/dossiers/demande-document",



    USER_PROFIL_DOSSIER_CONTRIBUABLE_BORNAGE: "http://localhost:4040/api/users/contribuable/dossiers/bornage",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_ATTRIBUTION: "http://localhost:4040/api/users/contribuable/dossiers/attribution",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_RETRAIT: "http://localhost:4040/api/users/contribuable/dossiers/retrait",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_EXONERATION: "http://localhost:4040/api/users/contribuable/dossiers/exoneration",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MANDAT: "http://localhost:4040/api/users/contribuable/dossiers/mandat",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MUTATION: "http://localhost:4040/api/users/contribuable/dossiers/mutation",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MORCELLEMENT: "http://localhost:4040/api/users/contribuable/dossiers/morcellement",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_CONTRIBUTION: "http://localhost:4040/api/users/contribuable/dossiers/contribution-fonciere",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_FUSION: "http://localhost:4040/api/users/contribuable/dossiers/fusion",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MISE_A_JOUR: "http://localhost:4040/api/users/contribuable/dossiers/mise-a-jour",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_AMENAGEMENT: "http://localhost:4040/api/users/contribuable/dossiers/amenagement",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_LOTISSEMENT: "http://localhost:4040/api/users/contribuable/dossiers/lotissement",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_DEMANDE_DOCUMENT: "http://localhost:4040/api/users/contribuable/dossiers/demande-document",


    INDIVISIONS_API:"http://localhost:4040/api/indivisions",
    IFU_API:"http://localhost:4040/api/ifu",
    NATIONALITE_API:"http://localhost:4040/api/nationalite",
    PROFESSION_API:"http://localhost:4040/api/profession",
    SITUATIONMATRIMONIALE_API:"http://localhost:4040/api/situation-matrimoniale",
    REGIME_FISCAL_API: "http://localhost:4040/api/regime-fiscal",
    SECTEUR_ACTIVITE_API: "http://localhost:4040/api/secteur-activite",
    TITREHONORIFIQUE_API:"http://localhost:4040/api/titre-honorifique",
    PARCELLE_API:"http://localhost:4040/api/parcelles",
    CONTRIBUABLE_AUTOCOMPLETE_API:"http://localhost:4040/api/contribuable",
    CONTRIBUABLE_AUTOCOMPLETE_MEMBRE_INDIVISION_API:"http://localhost:4040/api/contribuable/indivision-membre/autocomplete",
    SECTION_API: "http://localhost:4040/api/sections",
    GEOSERVER_API:"http://localhost:4040/api/geoserver",
    MENU_ICONE_API: "http://localhost:4040/api/menu/autocomplete/icone"
  },
  PUBLIC:{
    BUREAUX_PUBLIC_API:"http://localhost:4040/api/public/bureau",
    SERVICES_PUBLIC_API:"http://localhost:4040/api/public/service",
    STRUCTURES_PUBLIC_API:"http://localhost:4040/api/public/structure",
    STATUS_JURIDIQUE_API:"http://localhost:4040/api/public/status-juridique",
    CATEGORIES_PUBLIC_PIECE:"http://localhost:4040/api/public/categorie-piece",
    CIVILITES_PUBLIC_API:"http://localhost:4040/api/public/civilite",
    LOCALITE_PUBLIC_API:"http://localhost:4040/api/public/localite",
    QUARTIER_PUBLIC_API:"http://localhost:4040/api/public/quartier",
    CATEGORIES__PUBLIC_ACTEUR_API:"http://localhost:4040/api/public/categorie-acteur",
    NATIONALITE_PUBLIC_API:"http://localhost:4040/api/public/nationalite",
    PROFESSION_PUBLIC_API:"http://localhost:4040/api/public/profession",
    SITUATIONMATRIMONIALE_PUBLIC_API:"http://localhost:4040/api/public/situation-matrimoniale",
    REGIME_FISCAL_PUBLIC_API: "http://localhost:4040/api/public/regime-fiscal",
    SECTEUR_ACTIVITE_PUBLIC_API: "http://localhost:4040/api/public/secteur-activite",
    TITREHONORIFIQUE_PUBLIC_API:"http://localhost:4040/api/public/titre-honorifique"
  },

  FRONTEND_ROUTES: {
    SITE_EXTERNE:"site",
    VUE_360:"",
    BASE_VUE_360:"",
    PROFILE:"profile",
    CONTRIBUABLE_AGENT:"contribuables/agents",
    CONTRIBUABLE_INDIVISION:"contribuables/indivisions",
    CONTRIBUABLE_ACTEUR:"contribuables/acteurs",
    CONTRIBUABLE_PHYSIQUE:"contribuables/contribuable-physique",
    CONTRIBUABLE_MORAL:"contribuables/contribuable-moral",
    CONTRIBUABLE_PROFIL:"contribuables/profil",
    CONTRIBUABLE_VIEW_PROFIL:"contribuables/view-profil",
    CONTRIBUABLE_VIEW_PROFIL_ACTEUR:"contribuables/view-profil/acteur",
    CONTRIBUABLE_VIEW_PROFIL_AGENT:"contribuables/view-profil/agent",
    CONTRIBUABLE_VIEW_PROFIL_MORAL:"contribuables/view-profil/contribuable-moral",
    CONTRIBUABLE_VIEW_PROFIL_PHYSIQUE:"contribuables/view-profil/contribuable-physique",
    CONTRIBUABLE_VIEW_PROFIL_INDIVISION:"contribuables/view-profil/indivision",
    SECURITY_PROFILE:"security/profiles",
    SECURITY_ROLES:"security/roles",

    ORGANIGRAMME_BUREAU:"organisation/bureau",
    ORGANIGRAMME_SERVICE:"organisation/services",
    ORGANIGRAMME_TYPE_STRUCTURE:"organisation/type-structure",
    ORGANIGRAMME_STRUCTURE:"organisation/structure",
    ORGANIGRAMME_LIVRE_FONCIER: "organisation/livre_foncier",
    TERRITOIRE_LOCALITE:"territoire/localite",
    TERRITOIRE_ARRONDISSEMENT:"territoire/arrondissements",
    TERRITOIRE_COMMUNE:"territoire/communes",
    TERRITOIRE_PROVINCE:"territoire/provinces",
    TERRITOIRE_REGION:"territoire/regions",
    CONFIGURATION_STATUS_JURIDIQUE:"configuration/status-juridique",
    CONFIGURATION_RELATION_INDIVISION:"configuration/relation-indivision",
    CONFIGURATION_CATEGORIE_PIECE:"configuration/categorie-piece",
    CONFIGURATION_CATEGORIE_ACTEUR:"configuration/categorie-acteur",
    CONFIGURATION_CIVILITE:"configuration/civilites",
    CONFIGURATION_DATA_STORE:"configuration/data-store",
    CONFIGURATION_TEMPLATE_EMAIL:"configuration/template-email",
    CONFIGURATION_SITUATION_MATRIMONIALE:'configuration/situation-matrimoniale',
    SYSTEM_AUDIT:"audit",
    SYSTEM_LOGIN:"login",
    SYSTEM_RECUPERATION_COMPTE:"recuperation",
    SYSTEM_RECUPERATION_COMPTE_REDEFINIR_PASSWORD:"create-new-password/:code",
    SYSTEM_CREER_COMPTE:"creer-compte",
    SYSTEM_ERROR:"error",
    WORKFLOW: "workflow",
    PROCESSUS_EXONERATION: "processus/exoneration",
    PROCESSUS_PLAN_CADASTRAL_SECTIONNEMENT:"processus/plan-cadastral-sectionnement",
    PROCESSUS_PLAN_CADASTRAL_AMENAGEMENT:"processus/plan-cadastral-amenagement",
    PROCESSUS_PLAN_CADASTRAL_LOTISSEMENT:"processus/plan-cadastral-lotissement",
    PROCESSUS_PLAN_CADASTRAL_MAJ_PLAN_CADASTRE:"processus/mise-a-jour-plan-cadastral",
    PROCESSUS_PLAN_CADASTRAL_MORCELLEMENT:"processus/plan-cadastral-morcellement",
    PROCESSUS_PLAN_CADASTRAL_FUSION:"processus/plan-cadastral-fusion",
    PROCESSUS_CONTRIBUTION_FONCIERE:"processus/contribution-fonciere",
    PROCESSUS_ENTITES_CADASTRALES: "processus/entites-cadastrales",
    SAISIE_DIFFEREE_MAJ: "processus/mise-a-jour-plan-cadastral-saisie",
    SAISIE_DIFFEREE_SECTIONNEMENT: "processus/saisie-differee/sectionnement",
    SAISIE_DIFFEREE_PV_ATTRIBUTION: "processus/saisie-pv-attribution",
    CONFIGURATION_PROFESSION: "configuration/profession",
    CONFIGURATION_SECTEUR_ACTIVITE: "configuration/secteur-activite",
    CONFIGURATION_REGIME_FISCAL: "configuration/regime-fiscal",
    CONFIGURATION_NATIONALITE: "configuration/nationalite",
    CONFIGURATION_TITRE_HONORIFIQUE: "configuration/titre-honorifique",
    CONFIGURATION_TYPE_IMMEUBLE: "configuration-metier/type-immeuble",
    CONFIGURATION_TYPE_DOCUMENT: "configuration-metier/document-type",
    CONFIGURATION_DROIT_IMMOBILIER: "configuration-metier/droit-immobilier",
    CONFIGURATION_TYPE_TRANSITION: "configuration-metier/type-transition",
    CONFIGURATION_MOTIF_REJET: "configuration-metier/motif-rejet",
    CONFIGURATION_DOMAINE_FONCTIONNEL: "configuration-metier/domaine-fonctionnel",
    CONFIGURATION_DESTINATION_PARCELLE: "configuration-metier/destination-parcelle",
    CONFIGURATION_TYPE_BATIMENT: "configuration-metier/type-batiment",
    CONFIGURATION_QUARTIER: "configuration-metier/quartier",
    CONFIGURATION_ATTRIBUTION_SOURCE: "configuration-metier/cession-source",
    CONFIGURATION_TYPE_APPARTEMENT: "configuration-metier/amenagement-particulier-type",
    CONFIGURATION_CATEGORIE_IMMEUBLE: "configuration-metier/categorie-immeuble",
    CONFIGURATION_PLAN_SOURCE: "configuration-metier/plan-source",
    CONFIGURATION_COEFFICIENT: "configuration-metier/coefficient-vecr",
    CONFIGURATION_PARCELLE_BAREME: "configuration-metier/parcelle-bareme",
    CONFIGURATION_GESTION: "configuration-metier/gestion",
    CONFIGURATION_NATURE_IMPOT:"configuration-metier/nature-impot",
    CONFIGURATION_TYPE_TITRE_RECETTE: "configuration-metier/type-titre-recette",
    CONFIGURATION_ELEMENT_LIQUIDATION: "configuration-metier/element-liquidation",
    CONFIGURATION_PACKAGE_IMPOT: "configuration-metier/package-impot",
    CONFIGURATION_BATIMENT: "configuration-metier/batiment",
    CONFIGURATION_IMMEUBLE: "configuration-metier/immeuble",
    CONFIGURATION_AMENAGEMENT_PARTICULIER:"configuration-metier/amenagement-particulier",
    CONFIGURATION_PARCELLE_DELIMITATION: "bornage-delimitation",
    CONFIGURATION_EXONERATION_CATEGORIE: "configuration-metier/exoneration-categorie",
    CONFIGURATION_CATEGORIE_PIECE_PROCESSUS: "configuration-metier/categorie-piece-processus",
    CONFIGURATION_MODE_REGLEMENT: "configuration-metier/mode-reglement",
    CONFIGURATION_EXONERATION: "configuration-metier/exoneration",
    CONFIGURATION_SYSTEM_IMPOSITION: "configuration-metier/system-imposition",
    CONFIGURATION_DEGRE_SUCCESSORAL: "configuration-metier/degre-successoral",
    CONFIGURATION_EXERCICE_FISCALE: "configuration-metier/exercice-fiscale",
    CONFIGURATION_CALENDRIER_FISCALE:"configuration-metier/calendrier-fiscale",
    CONFIGURATION_BAREME_IMPOT: "configuration-metier/bareme-impot",
    CONFIGURATION_WORKFLOW: "configuration-processus",
    CONFIGURATION_FORMULE: "configuration-metier/formule",
    SAISIE_DIFFEREE_ATTRIBUTION: "saisie-differee/attribution",
    SAISIE_DIFFEREE_MUTATION: "saisie-differee/mutation",
    SAISIE_DIFFEREE_AFFECTATION: "saisie-differee/affectation",
    SAISIE_DIFFEREE_RETRAIT: "saisie-differee/retrait",
    SAISIE_DIFFEREE_DEMANDE_DOCUMENT: "saisie-differee/demandes-documents",
    SAISIE_DIFFEREE_DELIVRANCE_AAP: "delivrance/attestation-attribution-parcelle",
    PROCESSUS_BORNAGE_DELIMITATION: "processus/bornage-delimitation",
    PROCESSUS_FUSION: "processus/plan-cadastral-fusion",
    APP_MENU: "configuration/menu-utilisateur",
    CONFIGURATION_MANDAT: "contribuables/mandat",
    PROCESSUS_MANDAT: "processus/mandat",
    GESTION_INDEXATION: "configuration/indexation",
    GESTION_COMPTE: "processus/creation-compte-en-ligne",
    CONFIGURATION_WORKFLOW_CREATION_COMPTE: "configuration-processus/creation-compte-contribuable",
    INFORMATION_COMPTE: "information-compte"
  }


};






