// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: true,
  AUTH: {
    LOGIN_API:"/api/authentification",
    ME_API:"/api/users/moi",
    LOGOUT_API:"/api/logout",
    REFRESH_TOKEN_API:"/api/refresh-token",
    LIST_MY_ROLES:"/api/check-my-roles",
    CHECK_IF_I_AM_LIGIN:"/api/check-if-am-login",
    PREFERENCE_API: "/api/preference"
  },
  ORGANIGRAMME: {
    COMMUNES_API:"/api/communes",
    CATEGORIES_STRUCTURE_API: "/api/categorie-structures",
    BUREAUX_API:"/api/bureaux",
    SERVICES_API:"/api/services",
    STRUCTURES_API:"/api/structures",
    PREFERENCE_API:"/api/preference",
    LIVRE_FONCIER_API: "/api/livre_foncier"
  },
  REAL_TIME: {
    GLOBAL_INFO:"/api/stats/global-sessions-infos"

  },
  TERRITOIRE: {
    REGIONS_API:"/api/regions",
    PROVINCES_API:"/api/provinces",
    ARRONDISSEMENTS_API: "/api/arrondissements",
    COMMUNES_API: "/api/communes",
    LOCALITES_API:"/api/localites",
    PARCELLE_API:"/api/parcelles",
    ILOT_API:"/api/ilots",
  },
  CONFIGURATION: {
    TYPE_IMMEUBLE_API: "/api/type-immeuble",
    TYPE_DOCUMENT_API: "/api/type-document",
    DESTINATION_PARCELLE_API: "/api/destination",
    TYPE_BATIMENT_API: "/api/type-batiment",
    QUARTIER_API: "/api/quartier",
    ATTRIBUTION_SOURCE_API:  "/api/cession-source",
    ARRONDISSEMENT_ZONE_API: "/api/arrondissement-zone",
    AP_TYPE_API: "/api/amenagement-particulier-type",
    CATEGORIE_IMMEUBLE_API:"/api/categorie-immeuble",
    DROIT_IMMOBILIER_API:"/api/droit-immobilier",
    TYPE_TRANSITION_API:"/api/type-transition",
    MOTIF_REJET_API:"/api/motif-rejet",
    DOMAINE_FONCTIONNEL_API:"/api/domaine-fonctionnel",
    PLAN_SOURCE_API: "/api/plan-source",
    COEFFICIENT_API:  "/api/coefficient-vetus",
    PARCELLE_BAREME_API: "/api/bareme-parcelle",
    NATURE_IMPOT_API: "/api/nature-impot",
    TYPE_TITRE_RECETTE_API: "/api/type-titre-recette",
    ELEMENT_LIQUIDATION_API: "/api/element-liquidation",
    PACKAGE_IMPOT_API: "/api/package-impot",
    BATIMENT_API: "/api/batiment",
    IMMEUBLE_API:  "/api/immeuble",
    AMENAGEMENT_PARTICULIER_API:"/api/amenagement-particulier",
    PARCELLE_DELIMITATION_API:"/api/parcelle-delimitation",
    EXONERATION_CATEGORIE_API: "/api/exoneration-categorie",
    MODE_REGLEMENT_API: "/api/mode-reglement",
    TITRE_RECETTE_API: "/api/titre-recette",
    EXONERATION_API: "/api/exoneration",
    SYSTEM_IMPOSITION_API: "/api/system-imposition",
    DEGRE_SUCCESSORAL_API: "/api/degre-successoral",
    EXERCICE_FISCALE_API: "/api/exercice-fiscale",
    BAREME_IMPOT_API:"/api/bareme-impot",
    FORMULE_API: "/api/formule",
    CATEGORIE_PIECE_PROCESSUS_API: "/api/categorie-piece-processus",
    MANDAT_API: "/api/mandats",
    CYLE_DE_VIE: "/api/cyle-de-vie",
    CALENDRIER_FISCALE_API: "/api/calendrier-fiscale",
    QUITTANCE_SINTAX: "/api/quittance",

  },
  PROCESSUS: {
    PLAN_CADASTRAL_SECTIONNEMENT:"/api/processus/plan-cadastral-sectionnement",
    PLAN_CADASTRAL_AMENAGEMENT:"/api/processus/plan-cadastral-amenagement",
    PLAN_CADASTRAL_LOTISSEMENT:"/api/processus/plan-cadastral-lotissement",
    PLAN_CADASTRAL_MAJ_PLAN_CADASTRE:"/api/processus/mise-a-jour-plan-cadastral",
    PLAN_CADASTRAL_MORCELLEMENT:"/api/processus/plan-cadastral-morcellement",
    PLAN_CADASTRAL_FUSION:"/api/processus/plan-cadastral-fusion",
    PLAN_CADASTRAL_TOURNEE_DE_CONSERVATION:"/api/processus/plan-cadastral-tournee-de-conservation",
    TRANSITION:"/api/transitions",
    HISTORIQUE:"/api/historiques",
    PPROCESSUS:"/api/processus",
     BORNAGE_DELIMITATION:"/api/processus/bornage-delimitation",
    CONTRIBUTION_FONCIERE: "/api/processus/contribution-fonciere",
    PROCESSUS_MANDAT_API:"/api/processus/mandat",
    EXONERATION_API: "/api/processus/exoneration",

  },
  SAISIE_DIFFEREE: {

    SAISIE_DIFFEREE_ATTRIBUTION_API: "/api/processus/saisie-differee/attribution",
    SAISIE_DIFFEREE_MUTATION_API: "/api/processus/saisie-differee/mutation",
    SAISIE_DIFFEREE_AFFECTATION_API: "/api/processus/saisie-differee/affectation",
    SAISIE_DIFFEREE_RETRAIT_API: "/api/processus/saisie-differee/retrait",
    SAISIE_DIFFEREE_DEMANDE_DOCUMENT_API: "/api/processus/saisie-differee/demandes-documents",
    SAISIE_DIFFEREE_DELIVRANCE_AAP_API: "/api/processus/attestation_attribution_parcelle",
    SAISIE_DIFFEREE_MAJ_API:"/api/processus/saisie-differee/mise-a-jour-plan-cadastral",
    SAISIE_DIFFEREE_PV_ATTRIBUTION_API:"/api/processus/saisie-differee/entete-pv",
    SAISIE_DIFFEREE_ATTRIBUTION_CONTEXTE_API:"/api/SaisieDiffereeAttributionContexte",

    SAISIE_DIFFEREE_SECTIONNEMENT_API:"/api/processus/saisie-differee/sectionnement",
   },
  APPLICATION: {
    MENU_USER_API:"/api/menu-users",
    UPLOAD_FILE_API:"/api/file/upload",
    UPLOAD_FILE_API_PUBLIC:"/api/file/public/upload",
    AVATAR_API:"/api/file/download",
    STATUS_JURIDIQUE_API:"/api/status-juridique",
    CATEGORIES_PIECE:"/api/categorie-piece",
    CATEGORIES_PIECE_PROCESSUS:"/api/categorie-piece-processus",
    CIVILITES_API:"/api/civilite",
    CATEGORIES_ACTEUR:"/api/categorie-acteur",
    FILTRE_RECHERCHE_AVANCE_API:"/api/filtre-recherche-avance",
    PARAMETRES_API: "/api/parametres",
    INDIVISIONS_REALATION_API: "/api/indivision-relation",
    EXPORT_API: "/api/reports",
    EXPORT_PROCESSUS_DOSSIER: "/api/printer_report",
    TEMPLATE_EMAIL_API: "/api/template-email",
    AUDIT: "/api/audits",
    RECUPERATION_COMPTE: "/api/recover-password",
    MENU_API: "/api/menu",
    INDEXATION: "/api/indexation",
    NOTIFICATION_API: "/api/notifications"
  },
  SECURITY: {
    ROLES_API:"/api/roles",
    PERMISSIONS_API:"/api/permissions",
    PROFILES_API: "/api/profils",
    OTP_CONFIG_API: "/api/user-profil-edition/otp/config",
    OTP_CONFIG_VALIDATION_API: "/api/user-profil-edition/otp/validate-config",
    OTP_RESET_API: "/api/user-profil-edition/otp/reset",
    OTP_CHECK_API: "/api/user-profil-edition/otp/check",
    OTP_READER_CHECK_API: "/api/user-profil-edition/otp/reader-for-check",
  },
  USERS: {
    ACTEURS_API: "/api/acteurs",
    AGENTS_API:"/api/agents",
    CONTRIBUABLE_MORAL_API:"/api/contribuable-morales",
    CONTRIBUABLE_PHYSIQUE_API:"/api/contribuable-physiques",
    CONTRIBUABLE_API:"/api/contribuables",
    TRANSITION_FONCTIONNELLE_API:"/api/transition-fonctionnelle",

    CONTRIBUABLE_CHECK_API:"/api/contribuables/check",
    USER_PROFIL_EDITION_AVATAR: "/api/user-profil-edition/avatar",
    USER_PROFIL_EDITION_EMAIL: "/api/user-profil-edition/emails",
    USER_PROFIL_EDITION_ADRESSE:"/api/user-profil-edition/adresses",
    USER_PROFIL_EDITION_TELEPHONE:"/api/user-profil-edition/telephones",
    USER_PROFIL_EDITION_CREDENTIAL:"/api/user-profil-edition/credentials",
    NEW_COMPTE: "/api/processus/creation-compte-contribuable",
    NEW_COMPTE_PUBLIC: "/api/processus/creation-compte-contribuable/public",

    USER_PROFIL_DOSSIER_MOI_BORNAGE: "/api/users/moi/dossiers/bornage",
    USER_PROFIL_DOSSIER_MOI_ATTRIBUTION: "/api/users/moi/dossiers/attribution",
    USER_PROFIL_DOSSIER_MOI_RETRAIT: "/api/users/moi/dossiers/retrait",
    USER_PROFIL_DOSSIER_MOI_EXONERATION: "/api/users/moi/dossiers/exoneration",
    USER_PROFIL_DOSSIER_MOI_MANDAT: "/api/users/moi/dossiers/mandat",
    USER_PROFIL_DOSSIER_MOI_MUTATION: "/api/users/moi/dossiers/mutation",
    USER_PROFIL_DOSSIER_MOI_MORCELLEMENT: "/api/users/moi/dossiers/morcellement",
    USER_PROFIL_DOSSIER_MOI_CONTRIBUTION: "/api/users/moi/dossiers/contribution-fonciere",
    USER_PROFIL_DOSSIER_MOI_FUSION: "/api/users/moi/dossiers/fusion",
    USER_PROFIL_DOSSIER_MOI_MISE_A_JOUR: "/api/users/moi/dossiers/mise-a-jour",
    USER_PROFIL_DOSSIER_MOI_AMENAGEMENT: "/api/users/moi/dossiers/amenagement",
    USER_PROFIL_DOSSIER_MOI_LOTISSEMENT: "/api/users/moi/dossiers/lotissement",
    USER_PROFIL_DOSSIER_MOI_DEMANDE_DOCUMENT: "/api/users/moi/dossiers/demande-document",



    USER_PROFIL_DOSSIER_CONTRIBUABLE_BORNAGE: "/api/users/contribuable/dossiers/bornage",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_ATTRIBUTION: "/api/users/contribuable/dossiers/attribution",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_RETRAIT: "/api/users/contribuable/dossiers/retrait",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_EXONERATION: "/api/users/contribuable/dossiers/exoneration",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MANDAT: "/api/users/contribuable/dossiers/mandat",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MUTATION: "/api/users/contribuable/dossiers/mutation",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MORCELLEMENT: "/api/users/contribuable/dossiers/morcellement",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_CONTRIBUTION: "/api/users/contribuable/dossiers/contribution-fonciere",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_FUSION: "/api/users/contribuable/dossiers/fusion",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_MISE_A_JOUR: "/api/users/contribuable/dossiers/mise-a-jour",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_AMENAGEMENT: "/api/users/contribuable/dossiers/amenagement",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_LOTISSEMENT: "/api/users/contribuable/dossiers/lotissement",
    USER_PROFIL_DOSSIER_CONTRIBUABLE_DEMANDE_DOCUMENT: "/api/users/contribuable/dossiers/demande-document",


    INDIVISIONS_API:"/api/indivisions",
    IFU_API:"/api/ifu",
    NATIONALITE_API:"/api/nationalite",
    PROFESSION_API:"/api/profession",
    SITUATIONMATRIMONIALE_API:"/api/situation-matrimoniale",
    REGIME_FISCAL_API: "/api/regime-fiscal",
    SECTEUR_ACTIVITE_API: "/api/secteur-activite",
    TITREHONORIFIQUE_API:"/api/titre-honorifique",
    PARCELLE_API:"/api/parcelles",
    CONTRIBUABLE_AUTOCOMPLETE_API:"/api/contribuable",
    CONTRIBUABLE_AUTOCOMPLETE_MEMBRE_INDIVISION_API:"/api/contribuable/indivision-membre/autocomplete",
    SECTION_API: "/api/sections",
    GEOSERVER_API:"/api/geoserver",
    MENU_ICONE_API: "/api/menu/autocomplete/icone"
  },
  PUBLIC:{
    BUREAUX_PUBLIC_API:"/api/public/bureau",
    SERVICES_PUBLIC_API:"/api/public/service",
    STRUCTURES_PUBLIC_API:"/api/public/structure",
    STATUS_JURIDIQUE_API:"/api/public/status-juridique",
    CATEGORIES_PUBLIC_PIECE:"/api/public/categorie-piece",
    CIVILITES_PUBLIC_API:"/api/public/civilite",
    LOCALITE_PUBLIC_API:"/api/public/localite",
    QUARTIER_PUBLIC_API:"/api/public/quartier",
    CATEGORIES__PUBLIC_ACTEUR_API:"/api/public/categorie-acteur",
    NATIONALITE_PUBLIC_API:"/api/public/nationalite",
    PROFESSION_PUBLIC_API:"/api/public/profession",
    SITUATIONMATRIMONIALE_PUBLIC_API:"/api/public/situation-matrimoniale",
    REGIME_FISCAL_PUBLIC_API: "/api/public/regime-fiscal",
    SECTEUR_ACTIVITE_PUBLIC_API: "/api/public/secteur-activite",
    TITREHONORIFIQUE_PUBLIC_API:"/api/public/titre-honorifique"
  },

  FRONTEND_ROUTES: {
    SITE_EXTERNE:"site",
    VUE_360:"",
    BASE_VUE_360:"",
    PROFILE:"profile",
    CONTRIBUABLE_AGENT:"contribuables/agents",
    CONTRIBUABLE_INDIVISION:"contribuables/indivisions",
    CONTRIBUABLE_ACTEUR:"contribuables/acteurs",
    CONTRIBUABLE_PHYSIQUE:"contribuables/contribuable-physique",
    CONTRIBUABLE_MORAL:"contribuables/contribuable-moral",
    CONTRIBUABLE_PROFIL:"contribuables/profil",
    CONTRIBUABLE_VIEW_PROFIL:"contribuables/view-profil",
    CONTRIBUABLE_VIEW_PROFIL_ACTEUR:"contribuables/view-profil/acteur",
    CONTRIBUABLE_VIEW_PROFIL_AGENT:"contribuables/view-profil/agent",
    CONTRIBUABLE_VIEW_PROFIL_MORAL:"contribuables/view-profil/contribuable-moral",
    CONTRIBUABLE_VIEW_PROFIL_PHYSIQUE:"contribuables/view-profil/contribuable-physique",
    CONTRIBUABLE_VIEW_PROFIL_INDIVISION:"contribuables/view-profil/indivision",
    SECURITY_PROFILE:"security/profiles",
    SECURITY_ROLES:"security/roles",

    ORGANIGRAMME_BUREAU:"organisation/bureau",
    ORGANIGRAMME_SERVICE:"organisation/services",
    ORGANIGRAMME_TYPE_STRUCTURE:"organisation/type-structure",
    ORGANIGRAMME_STRUCTURE:"organisation/structure",
    ORGANIGRAMME_LIVRE_FONCIER:"organisation/livre_foncier",
    TERRITOIRE_LOCALITE:"territoire/localite",
    TERRITOIRE_ARRONDISSEMENT:"territoire/arrondissements",
    TERRITOIRE_COMMUNE:"territoire/communes",
    TERRITOIRE_PROVINCE:"territoire/provinces",
    TERRITOIRE_REGION:"territoire/regions",
    CONFIGURATION_STATUS_JURIDIQUE:"configuration/status-juridique",
    CONFIGURATION_RELATION_INDIVISION:"configuration/relation-indivision",
    CONFIGURATION_CATEGORIE_PIECE:"configuration/categorie-piece",
    CONFIGURATION_CATEGORIE_ACTEUR:"configuration/categorie-acteur",
    CONFIGURATION_CIVILITE:"configuration/civilites",
    CONFIGURATION_DATA_STORE:"configuration/data-store",
    CONFIGURATION_TEMPLATE_EMAIL:"configuration/template-email",
    CONFIGURATION_SITUATION_MATRIMONIALE:'configuration/situation-matrimoniale',
    SYSTEM_AUDIT:"audit",
    SYSTEM_LOGIN:"login",
    SYSTEM_RECUPERATION_COMPTE:"recuperation",
    SYSTEM_RECUPERATION_COMPTE_REDEFINIR_PASSWORD:"create-new-password/:code",
    SYSTEM_CREER_COMPTE:"creer-compte",
    SYSTEM_ERROR:"error",
    WORKFLOW: "workflow",
    PROCESSUS_EXONERATION: "processus/exoneration",
    PROCESSUS_PLAN_CADASTRAL_SECTIONNEMENT:"processus/plan-cadastral-sectionnement",
    PROCESSUS_PLAN_CADASTRAL_AMENAGEMENT:"processus/plan-cadastral-amenagement",
    PROCESSUS_PLAN_CADASTRAL_LOTISSEMENT:"processus/plan-cadastral-lotissement",
    PROCESSUS_PLAN_CADASTRAL_MAJ_PLAN_CADASTRE:"processus/mise-a-jour-plan-cadastral",
    PROCESSUS_PLAN_CADASTRAL_MORCELLEMENT:"processus/plan-cadastral-morcellement",
    PROCESSUS_PLAN_CADASTRAL_FUSION:"processus/plan-cadastral-fusion",
    PROCESSUS_CONTRIBUTION_FONCIERE:"processus/contribution-fonciere",
    PROCESSUS_ENTITES_CADASTRALES: "processus/entites-cadastrales",
    SAISIE_DIFFEREE_MAJ: "processus/mise-a-jour-plan-cadastral-saisie",
    SAISIE_DIFFEREE_SECTIONNEMENT: "processus/saisie-differee/sectionnement",
    SAISIE_DIFFEREE_PV_ATTRIBUTION: "processus/saisie-pv-attribution",
    CONFIGURATION_PROFESSION: "configuration/profession",
    CONFIGURATION_SECTEUR_ACTIVITE: "configuration/secteur-activite",
    CONFIGURATION_REGIME_FISCAL: "configuration/regime-fiscal",
    CONFIGURATION_NATIONALITE: "configuration/nationalite",
    CONFIGURATION_TITRE_HONORIFIQUE: "configuration/titre-honorifique",
    CONFIGURATION_TYPE_IMMEUBLE: "configuration-metier/type-immeuble",
    CONFIGURATION_TYPE_DOCUMENT: "configuration-metier/document-type",
    CONFIGURATION_DROIT_IMMOBILIER: "configuration-metier/droit-immobilier",
    CONFIGURATION_TYPE_TRANSITION: "configuration-metier/type-transition",
    CONFIGURATION_MOTIF_REJET: "configuration-metier/motif-rejet",
    CONFIGURATION_DOMAINE_FONCTIONNEL: "configuration-metier/domaine-fonctionnel",
    CONFIGURATION_DESTINATION_PARCELLE: "configuration-metier/destination-parcelle",
    CONFIGURATION_TYPE_BATIMENT: "configuration-metier/type-batiment",
    CONFIGURATION_QUARTIER: "configuration-metier/quartier",
    CONFIGURATION_ATTRIBUTION_SOURCE: "configuration-metier/cession-source",
    CONFIGURATION_TYPE_APPARTEMENT: "configuration-metier/amenagement-particulier-type",
    CONFIGURATION_CATEGORIE_IMMEUBLE: "configuration-metier/categorie-immeuble",
    CONFIGURATION_PLAN_SOURCE: "configuration-metier/plan-source",
    CONFIGURATION_COEFFICIENT: "configuration-metier/coefficient-vecr",
    CONFIGURATION_PARCELLE_BAREME: "configuration-metier/parcelle-bareme",
    CONFIGURATION_GESTION: "configuration-metier/gestion",
    CONFIGURATION_NATURE_IMPOT:"configuration-metier/nature-impot",
    CONFIGURATION_TYPE_TITRE_RECETTE: "configuration-metier/type-titre-recette",
    CONFIGURATION_ELEMENT_LIQUIDATION: "configuration-metier/element-liquidation",
    CONFIGURATION_PACKAGE_IMPOT: "configuration-metier/package-impot",
    CONFIGURATION_BATIMENT: "configuration-metier/batiment",
    CONFIGURATION_IMMEUBLE: "configuration-metier/immeuble",
    CONFIGURATION_AMENAGEMENT_PARTICULIER:"configuration-metier/amenagement-particulier",
    CONFIGURATION_PARCELLE_DELIMITATION: "bornage-delimitation",
    CONFIGURATION_EXONERATION_CATEGORIE: "configuration-metier/exoneration-categorie",
    CONFIGURATION_CATEGORIE_PIECE_PROCESSUS: "configuration-metier/categorie-piece-processus",
    CONFIGURATION_MODE_REGLEMENT: "configuration-metier/mode-reglement",
    CONFIGURATION_EXONERATION: "configuration-metier/exoneration",
    CONFIGURATION_SYSTEM_IMPOSITION: "configuration-metier/system-imposition",
    CONFIGURATION_DEGRE_SUCCESSORAL: "configuration-metier/degre-successoral",
    CONFIGURATION_EXERCICE_FISCALE: "configuration-metier/exercice-fiscale",
    CONFIGURATION_CALENDRIER_FISCALE:"configuration-metier/calendrier-fiscale",
    CONFIGURATION_BAREME_IMPOT: "configuration-metier/bareme-impot",
    CONFIGURATION_WORKFLOW: "configuration-processus",
    CONFIGURATION_FORMULE: "configuration-metier/formule",
    SAISIE_DIFFEREE_ATTRIBUTION: "saisie-differee/attribution",
    SAISIE_DIFFEREE_MUTATION: "saisie-differee/mutation",
    SAISIE_DIFFEREE_AFFECTATION: "saisie-differee/affectation",
    SAISIE_DIFFEREE_RETRAIT: "saisie-differee/retrait",
    SAISIE_DIFFEREE_DEMANDE_DOCUMENT: "saisie-differee/demandes-documents",
    SAISIE_DIFFEREE_DELIVRANCE_AAP: "delivrance/attestation-attribution-parcelle",
    PROCESSUS_BORNAGE_DELIMITATION: "processus/bornage-delimitation",
    PROCESSUS_FUSION: "processus/plan-cadastral-fusion",
    APP_MENU: "configuration/menu-utilisateur",
    CONFIGURATION_MANDAT: "contribuables/mandat",
    PROCESSUS_MANDAT: "processus/mandat",
    GESTION_INDEXATION: "configuration/indexation",
    GESTION_COMPTE: "processus/creation-compte-en-ligne",
    CONFIGURATION_WORKFLOW_CREATION_COMPTE: "configuration-processus/creation-compte-contribuable",
    INFORMATION_COMPTE: "information-compte"
  }


};






